--!strict

local RoundDurations = table.freeze({
	Waiting = 0,
	Intermission = 6,
	BriefChoice = 10,
	ThreadRun = 55,
	BeatLab = 40,
	PrismPuzzle = 40,
	MixLab = 60,
	Finale = 20,
	Results = 10,
	Cleanup = 2,
})

local Config = {
	GameName = "AURA RUSH: СТИЛЬ-РЕЙД",
	LegacyGameName = "AURA RUSH",
	Tagline = "Собери образ. Пройди район. Перекрась сцену.",
	ClientVersion = 6,
	SchemaVersion = 5,
	DataStoreName = "AuraRush_Profile_v1",
	RemoteFolderName = "AuraRushRemotes",
	MinimumPlayers = 1,
	MaximumPlayers = 12,
	AutosaveIntervalSeconds = 60,
	SessionLockSeconds = 180,
	ShutdownSaveBudgetSeconds = 25,
	Persistence = table.freeze({
		MaximumAttempts = 3,
		InitialRetryDelaySeconds = 0.35,
		BackoffMultiplier = 2,
		MaximumRetryDelaySeconds = 1.5,
		RequestBudgetWaitSeconds = 2,
		RequestBudgetPollSeconds = 0.1,
	}),
	RoundDurations = RoundDurations,

	FirstMiracle = table.freeze({
		Enabled = true,
		MaximumSeconds = 30,
		ChoiceSeconds = 8,
		ActionTarget = 3,
		ActionCooldownSeconds = 0.18,
		BloomSeconds = 4,
		CompletionGlowDust = 100,
		CompletionAtlasXp = 80,
		CompletionAtlasSchool = "Motion",
		CompletionAuraId = "aura_first_miracle",
		PaletteChoices = table.freeze({
			table.freeze({
				id = "palette_prism",
				nameKey = "first_miracle.palette.prism",
				colors = table.freeze({ "#FF4FD8", "#7657FF", "#38E8FF" }),
			}),
			table.freeze({
				id = "palette_cyan",
				nameKey = "first_miracle.palette.cyan",
				colors = table.freeze({ "#00D9FF", "#47F5D2", "#4062FF" }),
			}),
			table.freeze({
				id = "palette_sunset",
				nameKey = "first_miracle.palette.sunset",
				colors = table.freeze({ "#FF6B6B", "#FFB347", "#FFE66D" }),
			}),
		}),
		ActionSequence = table.freeze({
			table.freeze({
				id = "collect_thread",
				nameKey = "first_miracle.action.collect_thread",
			}),
			table.freeze({
				id = "tune_pulse",
				nameKey = "first_miracle.action.tune_pulse",
			}),
			table.freeze({
				id = "focus_prism",
				nameKey = "first_miracle.action.focus_prism",
			}),
		}),
	}),

	RunDirector = table.freeze({
		ActsPerRound = 3,
		RouteChoiceCount = 2,
		RecentRouteHistory = 5,
		MinimumDistinctCombinations = 1000,
		LateJoinMinimumSeconds = 12,
		BranchVoteSeconds = 8,
		DifficultyPerAdditionalPlayer = 0.08,
		MaximumDifficultyScale = 1.65,
	}),

	RemixCity = table.freeze({
		Version = 6,
		FirstWorldReactionSeconds = 15,
		FirstWowSeconds = 30,
		MaximumStoryboardMoments = 12,
		MaximumReplayEvents = 24,
		MaximumSavedReplays = 8,
		GuardianBaseTarget = 24,
		GuardianActionCooldownSeconds = 0.32,
		GuardianMinimumSeconds = 8,
		RoleChangeCooldownSeconds = 1,
		CityMemoryContributionPerRound = 12,
		CityMemoryMaximumDailyContribution = 180,
	}),

	SecretFrames = table.freeze({
		DiscoveryGlowDust = 35,
		DiscoveryCameraXp = 15,
		CollectionBonusGlowDust = 120,
		ActionCooldownSeconds = 1.5,
		DistancePaddingStuds = 3,
	}),

	Challenge = table.freeze({
		ThreadCheckpointCount = 5,
		ThreadCollectibleCount = 8,
		BeatCount = 12,
		BeatLaneCount = 4,
		BeatIntervalSeconds = 0.75,
		BeatPerfectWindowSeconds = 0.14,
		BeatGoodWindowSeconds = 0.28,
		PrismSequenceLength = 5,
		PrismColorCount = 4,
		PrismMaximumAttempts = 5,
		LightLoomNodeCount = 6,
		MaterialSurfGateCount = 7,
		BloomRescueTarget = 5,
		AssistAfterSeconds = 10,
	}),

	Rewards = table.freeze({
		RoundCompletion = 50,
		ThreadCheckpoint = 3,
		ThreadCollectible = 2,
		BeatPerfect = 3,
		BeatGood = 2,
		PrismSolved = 15,
		StyleReady = 5,
		MaximumPerRound = 150,
		GrantedRoundHistoryLimit = 30,
		AtlasXpCompletion = 45,
		AtlasXpChallenge = 8,
		AtlasXpDiscovery = 12,
		PositiveNominationXp = 3,
	}),

	Progression = table.freeze({
		MaximumCreativeRank = 100,
		MaximumSchoolLevel = 20,
		XpPerRank = 100,
		ParticipationShare = 0.7,
		MasteryShare = 0.3,
		Schools = table.freeze({ "Color", "Texture", "Motion", "Camera", "SetDesign" }),
	}),

	Quests = table.freeze({
		DailyCount = 3,
		DailyBankDays = 5,
		DailyFreeRerolls = 1,
		WeeklyCount = 4,
		SeasonWeeks = 8,
		SeasonNodes = 40,
	}),

	LiveOps = table.freeze({
		ManifestVersion = 2,
		CommunityEventId = "community_canvas_genesis",
		ContributionPerRound = 10,
		MaximumDailyContribution = 150,
		MemoryCacheSeconds = 45,
		AnnouncementTopic = "AuraRush_LiveOps_v2",
	}),

	-- Staff access is deliberately deny-by-default. Fill the owner IDs and/or
	-- group ID only in reviewed production configuration; no client can grant
	-- itself a role through the admin dashboard.
	Admin = table.freeze({
		Enabled = true,
		OwnerUserIds = table.freeze({}),
		GroupId = 0,
		GroupRanks = table.freeze({
			Admin = 200,
			Moderator = 100,
			Support = 50,
		}),
		AuditCapacity = 80,
		BroadcastCooldownSeconds = 20,
		AnnouncementTemplates = table.freeze({
			table.freeze({
				id = "maintenance_soon",
				toastKey = "toast.admin_notice_maintenance_soon",
				tone = "Warning",
			}),
			table.freeze({
				id = "update_ready",
				toastKey = "toast.admin_notice_update_ready",
				tone = "Success",
			}),
		}),
	}),

	DataLimits = table.freeze({
		MaximumSavedLooks = 20,
		MaximumLookNameLength = 24,
		MaximumUnlocksPerCategory = 256,
		MaximumGrantedRoundHistory = 30,
		MaximumGrantLedgerEntries = 180,
		MaximumQuestHistory = 90,
		MaximumPostcards = 24,
		MaximumSavedReplays = 8,
		MaximumReplayEvents = 24,
		MaximumPhotoModeUnlocks = 32,
	}),

	NetworkLimits = table.freeze({
		MaximumRoundIdLength = 80,
		MaximumItemIdLength = 48,
		MaximumBriefIdLength = 160,
		MaximumPrismSequenceLength = 8,
		MaximumClientClockSkewSeconds = 10,
	}),

	DefaultLoadout = table.freeze({
		palette = "palette_prism",
		material = "material_smooth",
		aura = "aura_spark",
		pose = "pose_hero",
		accent = "accent_orbit",
	}),

	FeatureFlags = table.freeze({
		Persistence = true,
		Analytics = true,
		Capture = true,
		FirstMiracle = true,
		AdaptiveRuns = true,
		Progression = true,
		NewChallenges = true,
		Postcards = true,
		EditablePostcards = false,
		ModularAudio = true,
		Purchases = false,
		Passes = false,
		MarketplaceCatalog = false,
		Subscriptions = false,
		Crews = true,
		LiveOps = true,
		CommunityBloom = true,
		ChallengeFramework2 = true,
		BloomComposer2 = true,
		SpatialFirstMiracle = true,
		LivingCity = true,
		StyleOS = true,
		RemixCity = true,
		StyleChemistry = true,
		GuardianFinales = true,
		ReplayGhosts = true,
		SeasonOne = true,
		CityPulse = true,
		SecretFrames = true,
		RecommendationService = false,
		PredictiveStreaming = true,
		ExperimentalMeshStreaming = false,
		ExperimentalAcoustics = false,
		RewardedVideo = false,
	}),

	Performance = table.freeze({
		TargetMobileFps = 30,
		TargetDesktopFps = 60,
		QualitySampleSeconds = 2,
		QualityRecoverySeconds = 20,
		MaximumServerScriptMilliseconds = 8,
		MaximumBloomHitchMilliseconds = 100,
		MaximumMemoryGrowthMbFiveRounds = 30,
	}),

	UI = table.freeze({
		DefaultLocale = "ru",
		SupportedLocales = table.freeze({ "ru", "en" }),
		MinimumTouchTarget = 48,
		ToastDurationSeconds = 3.5,
		ReducedMotionTweenScale = 0.15,
		LowVfxParticleScale = 0.25,
		NoFlashFrequencyHz = 3,
		MinimumAdjacentTouchSpacing = 8,
		ViewportPreviewTargetMilliseconds = 150,
	}),

	LivingCity = table.freeze({
		BloomThresholds = table.freeze({
			Dormant = 0,
			Stirring = 100,
			Blooming = 400,
			Radiant = 1000,
		}),
		CrossServerSyncInterval = 30,
		CrossServerTopic = "AuraRush_CityBloom_v1",
		ContributionPerRound = 14,
		MaximumDailyContribution = 200,
		Decay = table.freeze({
			DecayPerHour = 25,
			Floor = 0,
		}),
	}),
}

return table.freeze(Config)
